### ISSUE TITLE
OOBE failure: PKI decrypt

### ISSUE THREAD

**Issue by danielmarschall** [danielmarschall/oidplus#72]
Hallo @danielmarschall ,

Es gibt allerdings einen Punkt wo das OIDplus nicht "out-of-the-box" funktioniert ;-)
Habe hier https://oidplus.com/download.php das Archiv runtergeladen, aber untenstehende Meldung erscheint immer im letzten Schritt der Installation.
Habe sowohl die Datei als auch in der DB den Key gelöscht, aber es tut sich nix.
Kannst Du mal bitte schauen, wenn Du Zeit hast? Danke!
Die Installation liegt in test.weid.info in im weid.info Account.

Viele Grüße
Melanie

OIDplus Error
The Private/Public key-pair is broken or cannot be decrypted! Please check if the file /var/www/vhosts/weid.info/test.weid.info/httpdocs/public/userdata/secret/privkey_secret_207310503.php is existing and OK! In case this file is missing or corrupted and cannot be recovered, you need to reset your private/public key-pair. Do so by removing the settings oidplus_public_key and oidplus_private_key in the OIDplus configuration table in the database. This will invoke a regeneration of the private/public key-pair (you will receive a new system ID).
Technical information about the problem:

ViaThinkSoft\OIDplus\Core\OIDplusException
at file .../includes/classes/OIDplus.class.php (line 1886)

Stacktrace:
#0 .../includes/classes/OIDplus.class.php(1354): ViaThinkSoft\OIDplus\Core\OIDplus::getPkiStatus()
#1 .../index.php(32): ViaThinkSoft\OIDplus\Core\OIDplus::init()
#2 {main}

_Originally posted by @wehowski in https://github.com/frdl/frdl-oidplus-wtf-plugin/issues/2#issuecomment-2346883029_

**Comment by danielmarschall** [comment]
In the files there is a file privkey_secret_.php

I had to rename it to privkey_secret_207310503.php

So I need to look why the filename was wrong when the file was created.

**Comment by danielmarschall** [comment]
Bug introduced:
```
        {
                "version": "2.0.1.27",
                "date": "2024-07-19 13:00:00 +0200",
                "author": "Daniel Marschall (ViaThinkSoft)",
                "changes": [
                        "In case the private/public key pair is broken or cannot be decrypted, it will not be regenerated automatically.",
                        "The privkey secret file filename now contains the system ID, so it is easier to recognize"
                ]
        },
```

... so, less than 2 months broken. I hope that's ok
